---
- name: Install maven, git
  hosts: localhost
  become: yes

  tasks:
    - name: Install packages
      apt:
        name: " {{ item }} "
        state: present
      with_items:
        - maven
        - git

- name: Boxfuse application build
  hosts: localhost
  become: yes

  tasks:
    - name: Clone a github repository
      git:
        repo: https://github.com/boxfuse/boxfuse-sample-java-war-hello.git
        dest: /tmp/boxfuse-sample-java-war-hello
        clone: yes
        update: yes

    - name: Get Boxfuse artifact from Maven
      shell: "mvn package"
      args:
        chdir: /tmp/boxfuse-sample-java-war-hello

- name: Launching application in tomcat
  hosts: web
  become: yes

  tasks:
    - name: Install default-jdk, tomcat
      apt:
        name: " {{ item }} "
        state: present
      with_items:
        - default-jdk
        - tomcat9

    - name: Transfer WAR File to web
      copy:
        src: /tmp/boxfuse-sample-java-war-hello/target/hello-1.0.war
        dest: /var/lib/tomcat9/webapps/

    - name: Ensure tomcat is present
      service:
        name: tomcat9
        state: started
