---
- name: Install maven, git
  hosts: localhost
  become: yes

  tasks:
    - name: Install packages
      apt:
        name: " {{ packages }} "
        state: present
        with packages:
          - maven
          - git

- name: Boxfuse application build
  hosts: localhost
  become: yes

  tasks:
    - name: Clone a github repository
      git:
        repo: https://github.com/boxfuse/boxfuse-sample-java-war-hello.git
        dest: /tmp/boxfuse-sample-java-war-hello
        clone: yes
        update: yes

    - name: Download Boxfuse artifact from Maven Local
      shell: "mvn package"
        arg:
        chdir: tmp/boxfuse-sample-java-war-hello

- name: Launching application in tomcat
  hosts: web
  become: yes

  tasks:
    - name: Install default-jdk, tomcat
      apt:
        name: " {{ packages }} "
        state: present
        with packages:
          - default-jdk
          - tomcat

    - name: Transfer WAR File to web
      synchronize:
        src: /target/hello-1.0.war
        dest: /usr/local/tomcat/webapps/
        delegate_to: 212.111.84.186

    - name: Ensure tomcat is present
      service:
        name: tomcat
        state: started
